version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: gather
      POSTGRES_USER: composeUser
      POSTGRES_PASSWORD: composePassword
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: ${PWD}
      dockerfile: Dockerfile.dev
    volumes:
      - ${PWD}:/opt/code
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "start:debug"]
volumes:
  pgdata: